# Generated by Django 5.0.6 on 2024-07-08 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_model',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='recruiter_model',
            old_name='user',
            new_name='recruiter_user',
        ),
        migrations.RenameField(
            model_name='seeker_model',
            old_name='user',
            new_name='seeker_user',
        ),
    ]
